# Login user
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Jim"
}

###

# Refresh access token
POST http://localhost:4000/refresh_token
Content-Type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjY1MjI4MDU3fQ.SEG9eTfw6--S8qwpNi6C2HlHjOpqiVLPwZkPxsgx9sQ"
}

###

# Posts for current user
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjY1MjI4MTUyLCJleHAiOjE2NjUyMjgyMTJ9.YN728fBuGym8taq3X61LOHHru6rKmN0IhPqUBRHjRjM
